// File attachment in message
export interface MessageFile {
  id: string;
  name: string;
  path: string;
}

// Structured error from AI providers
export interface StructuredError {
  errorType: 'unknown-error' | 'feature-not-supported' | 'invalid-input' | 'api-error' | 'sidecar-error';
  shortMessage?: string;
  message?: string;
  suggestion?: string;
  suggestions?: string[]; // Multiple suggestions from sidecar errors
  technicalDetails?: string; // stderr or other debug info
}

// ChatMessage type used across the application
export interface ChatMessage {
  id: string;
  type: 'user' | 'assistant';
  content: string; // For display (kept for backward compatibility)
  messageTextWithFileContentsSentToAI?: string; // Full content including file data for conversation history
  timestamp: Date;
  sourceText?: string;
  images?: Array<{
    data: string;
    width: number;
    height: number;
  }>;
  files?: MessageFile[];
  isError?: boolean;
  structuredError?: StructuredError; // Structured error information
  tokenCount?: number; // Total tokens (for backward compatibility)
  inputTokens?: number; // Tokens sent to AI
  outputTokens?: number; // Tokens generated by AI
  reasoning?: string;
  isStreaming?: boolean;
  arxiv_papers?: import('@/api/types/ai').ArxivPaperMeta[];
  user_intent?: import('@/api/types/ai').UserIntent;
}

// Answer modes for AI responses
export type AnswerMode = 'short' | 'concise' | 'detailed';

// Props for the main AiChatPanel component
export interface AiChatPanelProps {
  selectedModel?: string;
  'data-testid'?: string;
}

// Image data structure
export interface PendingImage {
  data: string;
  width: number;
  height: number;
}

// Preview image structure
export interface PreviewImage {
  data: string;
  name: string;
  size: { width: number; height: number };
}

// PDF extraction result
export interface PdfExtractionResult {
  metadata: { page_count: number };
  pages: Array<{ page_number: number; text: string }>;
  success: boolean;
  error?: string;
}

// Chat history item
export interface ChatHistoryItem {
  id: string;
  title: string;
  timestamp: Date;
  messages: ChatMessage[];
  messageCount?: number;
  lastMessage?: string;
}